### ISSUE TITLE
Delete Button does not dissappear

### ISSUE THREAD

**Issue by juliajuju93** [Azure/api-center-preview#13]
# Description

After deleting an API in APIC, delete button stays
![image](https://github.com/Azure/api-center-preview/assets/42241691/2b56e7e0-c151-40db-b3a4-c811369cf8fa)

API Center instance name: APICStagingJulia

# Expected behavior

After hitting Yes button, screen should disappear.

**Comment by pierceboggan** [comment]
This doesn't reproduce anymore. Marking as closed.
