### ISSUE TITLE
Where is the developer portal?

### ISSUE THREAD

**Issue by apb-aursel** [Azure/api-center-preview#16]
# What are you trying to achieve?

After watching the video "Azure API Center and ASP.NET Web API Integration: A Developer's Guide | .NET Conf 2023" https://www.youtube.com/watch?v=o4gMJfee4iA, I would like to know how to create the developers portal shown there?
![image](https://github.com/Azure/api-center-preview/assets/67052185/8a7aafd0-48e7-4a54-8991-58f556307847)

# Proposed solution

Instructions how to do it.

# Alternative solutions

N/A

# Additional context

N/A

**Comment by juliajuju93** [comment]
Hi @apb-aursel - thanks for reaching out! 
Access to the developer portal will be part of our next (December release). We will keep you posted here and also via our other channels like Azure Update notes.

**Comment by StigLotuft** [comment]
Hi @juliajuju93 - any updates on this issue? Looking forward to testing this functionality.

**Comment by achrafbenalaya** [comment]
Hello, i'm following this and can't wait to test it ! any updates ?

**Comment by juliajuju93** [comment]
Hi all,
@apb-aursel , @achrafbenalaya , @StigLotuft:
I am excited to share that this is now officially rolled out 🥳.
Following these docs, you should be able to get the portal enabled: https://learn.microsoft.com/en-us/azure/api-center/enable-api-center-portal 

Please reach out if you have any future requests on this or on API Center in general! Looking forward to hearing your feedback :)
