### ISSUE TITLE
API Center Portal - Login Prompt appears then quickly disappears not allowing user to enter credentials

### ISSUE THREAD

**Issue by jharbieh-microsoft** [Azure/api-center-preview#19]
##Description
The Sign In button prompt dialog appears and quickly disappears without allowing the use to enter proper credentials. No consent dialog is shown either. 

## Reproduction steps
Followed the directions posted here to configure API Center Portal
https://learn.microsoft.com/en-us/azure/api-center/enable-api-center-portal

## Expected behavior
User is promoted and shown a login dialog to Sign In. At least 1st time through the process. Tenant accounts can be in the form of Cloud only, Federated or External (EXT), or Corporate synched account. 

## Actual behavior
I used different scenarios. All produced the same. 

1st. I am signed in to my browser using a corporate account that has been configured with access according to the documentation. 2nd. Same as 1st but with a private browser session. 
3rd. Configured a cloud-only account in the Entra tenant.

## Error messages (From browser developer tools dialog)
Error number one. Was leading me to re-think the user login/credential as well as application registration. 
_"error": "invalid_tenant", "error_description": "AADSTS90002: Tenant 'undefined' not found. Check to make sure you have the correct tenant ID and are signing into the correct cloud._

Error number two. Was not expected. 
_Uncaught (in promise) BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.   For more visit: aka.ms/msaljs/browser-errors_

## Additional context
Configured the API Center portal in 2 different Entra tenants. Same result. In some cases, the login prompt would not even come up. Consent is not shown.

**Comment by Bruce-Moe** [comment]
Thanks for bringing this issue to our attention @jharbieh-microsoft. This issue was caused by a build version issue in the East US region and should now be resolved. Could you try deleting and then recreating the Entra ID configuration in the Azure portal UI and then see if sign-in works?

**Comment by jharbieh-microsoft** [comment]
Thanks @Bruce-Moe It worked as expected!  A couple of variances. 

On my MSDN Azure benefit subscription with a @live.com account all is well. Consent was provided by the @live.com User. However, on my corporate tenant it still required Admin Consent even though the API Permissions screen says otherwise. 

![image](https://github.com/Azure/api-center-preview/assets/78561415/392406e5-d8a1-479c-98fc-49b3d79d54be)

I am thinking Tenant Admins might still have a policy that overrides what we configured in our App Registration. I don't know. 

Thoughts? 

Thanks for looking into this.

**Comment by jharbieh-microsoft** [comment]
Thanks @Bruce-Moe I appreciate you spending time on this. I will close this issue. All good here.
