### ISSUE TITLE
hyphen characters in the Identification field result in 

### ISSUE THREAD

**Issue by MassimoC** [Azure/api-center-preview#2]
# Description

A clear and concise description of what the bug is. Note that we are unable to provide product support within this repository - if you need assistance with using API Center, request support in the Azure portal.

# Reproduction steps

1. Go to Metadata schema 
2. Add a new property and fill the mandatory fields
3. Set "Object" as Type
4. Click 'Add object property'
5. Set the mandatory fields
6. In the 'Identification' field add an hyphen (for example 'ho-la')
7. Set String as type
8. Press Save
9. Press Next
10. Press Next
11. Press Create

# Expected behavior

The UI should validate the input or the final procedure should complete

# Actual behavior

The creation process start but fails with the following message

![image](https://github.com/Azure/api-center-preview/assets/8393694/867c6cc7-9949-4232-b7bd-4a7958929529)

# Screenshots

This configuration won't work

![image](https://github.com/Azure/api-center-preview/assets/8393694/d19c45ba-ed3e-44e1-b171-101e0aa4132f)

**Comment by azaslonov** [comment]
Thanks for reporting the bug @MassimoC!

**Comment by pierceboggan** [comment]
@MassimoC - This should now be fixed:
![image](https://github.com/Azure/api-center-preview/assets/1091304/1be4e333-3214-4fe9-b0e3-690775b9d2e1)

If you observe different behavior, please let us know. Thanks!
