### ISSUE TITLE
Update API definition directly on the Portal or VS Code extension

### ISSUE THREAD

**Issue by justinyoo** [Azure/api-center-preview#27]
# What are you trying to achieve?

Related to #26 

Currently, uploading API definition document through Azure CLI or Azure Portal is the only way to update the API definition. However, users should be able to update the definition directly on the Portal or in VS Code.

Once the update is done, the version number should be automatically incremented.

# Proposed solution

- Give the capability on Azure Portal to update API definitions.
- Give the capability to VS Code extension to update API definitions.
- Once updated through either Azure Portal or VS Code, the version number should automatically be incremented.

# Alternative solution

- For the API definition update, we should rely on CI/CD pipeline where it calls Azure CLI to update it, when the updated API definition is pushed to the repository. But it's too complicated for minor updates like correcting typos.

**Comment by pierceboggan** [comment]
@justinyoo This is now supported in the 0.2.0+ release of the API Center extension for Visual Studio Code.

**Comment by pierceboggan** [comment]
Updating #26 to be strictly for Azure portal support, and use this one for the VS Code extension.
