### ISSUE TITLE
Importing APIs from APIM shows random numbers instead of their respective API names and API IDs

### ISSUE THREAD

**Issue by justinyoo** [Azure/api-center-preview#29]
# Description

- `az`: `2.57.0`
- `az apic-extension`: `1.0.0b4`
- Azure API Center extension: `v0.1.0`
- OS: Windows 11

![image](https://github.com/Azure/api-center-preview/assets/1538528/1a9e8daa-3ade-4091-9164-a0bf9b68cf94)

I imported the API from APIM through Azure CLI.

```bash
APIM_RESOURCE_ID=$(az apim show -g "my-resource-group" -n "my-api-management" --query "id" -o tsv)
az apic service import-from-apim -g "my-resource-group" -s "my-api-center" --source-resource-ids "$APIM_RESOURCE_ID/apis/*"
```

The import itself was OK. But like the screenshot above, the APIM-imported API shows a ransom number, instead of its API-ID.

# Reproduction steps

1. Add an API to APIM
2. Add the role to APIC and add it to APIM
3. Import the API from APIM to APIC
4. See the result like above

# Expected behavior

- The API Center should display the proper API name, instead of the random number.

# Actual behavior

- The API Center shows the random number on the APIM-imported API as its name.

**Comment by pierceboggan** [comment]
This is a known issue that is fixed in our next Visual Studio Code extension release.

Thanks for reporting!
