### ISSUE TITLE
Support array of objects

### ISSUE THREAD

**Issue by MassimoC** [Azure/api-center-preview#3]
# What are you trying to achieve?

I would like to use API Center to track API Dependencies therefore I need to add an "array of objects" to the metadata.
Every object will have schema like 
- depends on (service it depends on)
- motivation (description of the dependency)
- type (e.g. API, DB, etc..)
- location (e.g. internal / external)

# Proposed solution

Support an array of object

# Alternative solutions

N/A

# Additional context

Array of objects is not supported

![image](https://github.com/Azure/api-center-preview/assets/8393694/ac4b7d78-3f1c-476a-828f-429a30e6e2cc)

**Comment by azaslonov** [comment]
@MassimoC, yup we've got this in Backlog as high-priority item. We'll keep you posted.

**Comment by pierceboggan** [comment]
This should be resolved in the latest Azure API Center preview.

![image](https://github.com/Azure/api-center-preview/assets/1091304/68c5e505-0758-4c9c-bd8e-34bab9b385a7)

Don't hesitate to reach out if you have any feedback on adding an array of objects.
