### ISSUE TITLE
APIs imported from APIM is disabled the right-click context menu pop-up

### ISSUE THREAD

**Issue by justinyoo** [Azure/api-center-preview#30]
# Description

- `az`: `2.57.0`
- `az apic-extension`: `1.0.0b4`
- Azure API Center extension: `v0.1.0`
- OS: Windows 11

![image](https://github.com/Azure/api-center-preview/assets/1538528/2a04af1c-a80b-475e-985b-a1e4e8982f4e)

Related to #29 

After importing APIs from APIM through Azure CLI, it's not able to use the context menu by right-mouse clicking.

As you can see the screenshot, registering APIs directly from Azure Portal or Azure CLI makes the right-mouse-click context menu enabled. However, APIs imported from APIM doesn't.

# Reproduction steps

1. Import APIs from APIM through Azure CLI
2. Right-mouse click on the API definition of the APIs imported from APIM
3. No context menu is popped-up

# Expected behavior

- The context menu should be displayed.

# Actual behavior

- The context menu doesn't get displayed.

**Comment by pierceboggan** [comment]
This is a known issue that is fixed in our next Visual Studio Code extension release. 

Thanks again for reporting!
