### ISSUE TITLE
VSCode extension - Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by Viktorh89** [Azure/api-center-preview#32]
# Description

After installing the extension, getting this error:
Cannot read properties of undefined (reading 'id')

Also not able to view any api definitions (right-click)

# Reproduction steps

1. install extension

![image](https://github.com/Azure/api-center-preview/assets/6905706/9e1a9116-c078-4d54-a281-389792776d20)

**Comment by Viktorh89** [comment]
The error seems to be gone now, but still cant interactive with any defintions or api by right clicking

**Comment by pierceboggan** [comment]
@Viktorh89 - Did you import these APIs using the Import from API Management functionality in Azure CLI? If so, this is an issue that is fixed. I can share a build with you for our upcoming February release if you email me at piboggan@microsoft.com. Thanks!

**Comment by juliajuju93** [comment]
In the newest updates of the VS code extension, this got fixed @pierceboggan, @Viktorh89
