### ISSUE TITLE
Identifier for API is a random string instead of API Name

### ISSUE THREAD

**Issue by Viktorh89** [Azure/api-center-preview#33]
# Description

If you create a manual API in Api Center, the name of the api also becomes the identifier. But while importing from APIM, seems all apis get a random identifier

# Reproduction steps

1.  Import from APIM (/apis*)

# Expected behavior

API name and identifier should be same

# Actual behavior

API name and identifier are not same

# Screenshots

![image](https://github.com/Azure/api-center-preview/assets/6905706/4e32fd0e-4661-45eb-8f42-19ad8a2acdf9)

![image](https://github.com/Azure/api-center-preview/assets/6905706/d5a9b541-f373-4702-b183-1ba6a97e7f8e)

**Comment by UniperMaster** [comment]
Has this been fixed and I cant see a commit or any reason for the closing

**Comment by Viktorh89** [comment]
yes i wrote a comment but it maybe didnt save,

its related to #32

see comment from @pierceboggan
