### ISSUE TITLE
Support for AsyncAPIs

### ISSUE THREAD

**Issue by LarsTheGreat** [Azure/api-center-preview#8]
# What are you trying to achieve?
We are building a catalog for enterprise services for APIs. This will include both REST APIs and Event Hubs for EVENTs.
For REST APIs we have the built in Developer Portal (in Azure APIM) for REST APIs, but we are also looking into building our own catalog for EVENTs. This will use  AsyncAPIs (https://www.asyncapi.com/) specifications to describe the EVENTs.

If we could use the same "API Center" catalog for both REST and EVENT it would simplify maintenance (i.e.. we don't need to build our own solution) for the platform team an hopefully give developers a better experience such as a one-stop-shop for all  (synchronous and asynchronous) APIs.  

# Proposed solution
Add support for AsyncAPI specifications in API center as a API Type. 
![image](https://github.com/Azure/api-center-preview/assets/106594183/fceeb67d-8c4d-457b-96de-1a1672b0ff8b)

# Alternative solutions
Of course an integration to Azure Event Hubs would be best but could be at a later stage.

# Additional context

**Comment by danradford** [comment]
I'd like to add a vote for AsyncAPI support

**Comment by fi0l** [comment]
following

**Comment by aczarkowski** [comment]
That would be great feature

**Comment by RickOttenNS** [comment]
According to the [documention](https://learn.microsoft.com/en-us/azure/api-center/key-concepts), this should be there.

**Comment by pierceboggan** [comment]
@LarsTheGreat @danradford @aczarkowski AsyncAPI specification documents are supported:

![image](https://github.com/Azure/api-center-preview/assets/1091304/522dc5ad-a8c8-4660-bccb-b640a5a6f35c)

![image](https://github.com/Azure/api-center-preview/assets/1091304/1420d6aa-1b44-458e-b2c9-0d5da4026a2f)
