### ISSUE TITLE
Upload Open API file populates APIs and schemas

### ISSUE THREAD

**Issue by mikaelsand** [Azure/api-center-preview#9]
# What are you trying to achieve?

The whole experience is underwhelming. Everything is manual and I basically have to copypaset everything from the API portal.
I would like to upload an open api file, or point to a URL and the documentation is populated using the data in the open api definition.

# Proposed solution

Either you upload a file or you will have to enter everything manually.

# Alternative solutions

Point to a URL containing the open api definition.

# Additional context

As it stands, the API Center is not very usable.
Sorry.

**Comment by pierceboggan** [comment]
@mikaelsand - You can now upload an API definition via an URL. Give it a try and let us know what you think!

![image](https://github.com/Azure/api-center-preview/assets/1091304/53e849be-d9cb-47ae-9d8b-77952e74a60c)

You can also import APIs to API Center using the Azure CLI command `az apic api register` and provide a specification document, and an API, version, and definition will be created automatically from the specification document. If you use Azure API Management, you can now use our Azure CLI import-from-apim command to bring in some or all APIs from an API Management instance.
